import { getDestination, buildPlan } from './api.js';
const $ = (id) => document.getElementById(id); const saved = JSON.parse(localStorage.getItem('trip-plan') || 'null');
function money(value, symbol) { return `${symbol}${value.toLocaleString()}`; }
const details = {
	Seoul: { weather: 'Cool, dry winters; warm humid summers. Spring and autumn are usually the easiest seasons for walking.', apps: [['Naver Map', 'Local maps and walking routes', 'https://map.naver.com/'], ['Papago', 'Korean translation', 'https://papago.naver.com/'], ['Kakao T', 'Taxi booking', 'https://www.kakaomobility.com/'], ['Korail', 'KTX train reservations', 'https://www.letskorail.com/']], hotel: 'https://www.booking.com/city/kr/seoul.html' },
	Busan: { weather: 'Milder by the coast, with hot humid summers and a comfortable spring and autumn for beaches and temples.', apps: [['Naver Map', 'Local maps and transit', 'https://map.naver.com/'], ['Papago', 'Korean translation', 'https://papago.naver.com/'], ['Kakao T', 'Taxi booking', 'https://www.kakaomobility.com/'], ['Korail', 'KTX train reservations', 'https://www.letskorail.com/']], hotel: 'https://www.booking.com/city/kr/busan.html' },
	Paris: { weather: 'Mild but changeable. Pack a light layer and rain protection in every season.', apps: [['Google Maps', 'Walking and transit', 'https://maps.google.com/'], ['Citymapper', 'Public transport', 'https://citymapper.com/'], ['DeepL', 'Translation', 'https://www.deepl.com/translator'], ['SNCF Connect', 'Train reservations', 'https://www.sncf-connect.com/']], hotel: 'https://www.booking.com/city/fr/paris.html' },
	Tokyo: { weather: 'Distinct seasons, rainy early summers, and hot humid Augusts. Spring and late autumn are popular for good reason.', apps: [['Google Maps', 'Walking and rail routes', 'https://maps.google.com/'], ['Japan Travel', 'Rail planning', 'https://www.japan.travel/en/'], ['Google Translate', 'Translation', 'https://translate.google.com/'], ['SmartEX', 'Shinkansen reservations', 'https://smart-ex.jp/en/']], hotel: 'https://www.booking.com/city/jp/tokyo.html' }
};
function getDetails(plan) { return details[plan.name] || { weather: 'Check the local forecast before departure and pack for the season, with one flexible layer for changing conditions.', apps: [['Google Maps', 'Walking and transit', 'https://maps.google.com/'], ['Google Translate', 'Translation', 'https://translate.google.com/'], ['Booking.com', 'Accommodation search', 'https://www.booking.com/'], ['Rome2Rio', 'Route planning', 'https://www.rome2rio.com/']], hotel: `https://www.booking.com/searchresults.html?ss=${encodeURIComponent(plan.name)}` }; }
function render(plan) { const info = getDetails(plan); $('plan').innerHTML = `<div class="plan-head"><div><p class="eyebrow">YOUR FIELD ROUTE</p><h2>${plan.name}, ${plan.country}</h2><p>${plan.itinerary.length} days / ${plan.currency} estimate</p></div><div class="cost"><span>ESTIMATED TOTAL</span><strong>${money(plan.total, plan.symbol)}</strong><small>${money(plan.daily, plan.symbol)} per day · ${$('style').selectedOptions[0].text}</small></div></div><div class="days">${plan.itinerary.map((day) => `<article class="day"><span class="day-number">DAY ${String(day.day).padStart(2, '0')}</span><div><h3>${day.places.join(' + ')}</h3><p>${day.note}</p></div><span class="day-cost">${money(plan.daily, plan.symbol)}</span></article>`).join('')}</div><div class="trip-details"><article class="detail-card weather-detail"><p class="eyebrow">WEATHER TO EXPECT</p><h3>Pack for the season.</h3><p>${info.weather}</p><a href="weather-travel/">Check the live forecast ↗</a></article><article class="detail-card"><p class="eyebrow">USEFUL APPS</p><h3>Download before you go.</h3><div class="resource-list">${info.apps.map(([name, purpose, url]) => `<a href="${url}" target="_blank" rel="noreferrer"><strong>${name}</strong><span>${purpose} ↗</span></a>`).join('')}</div></article><article class="detail-card budget-detail"><p class="eyebrow">TRIP COST</p><h3>${money(plan.total, plan.symbol)} for ${plan.itinerary.length} days</h3><p>Daily estimate: ${money(plan.daily, plan.symbol)}. This covers local transport, meals, and entry tickets. Flights and hotels are separate.</p><a href="currency-converter/">Check exchange rates ↗</a></article><article class="detail-card hotel-detail"><p class="eyebrow">STAY SOMEWHERE GOOD</p><h3>Reserve your hotel.</h3><p>Compare available rooms and locations near your first stop.</p><a class="hotel-button" href="${info.hotel}" target="_blank" rel="noreferrer">Search hotels in ${plan.name} ↗</a></article></div><p class="estimate-note">Estimates are planning guides, not live prices. Check transport, weather, entry rules, and hotel cancellation terms before booking.</p>`; }
$('planner-form').addEventListener('submit', (event) => { event.preventDefault(); const plan = buildPlan(getDestination($('destination').value), Number($('days').value), $('style').value); render(plan); localStorage.setItem('trip-plan', JSON.stringify(plan)); });
if (saved) { $('destination').value = saved.name; $('days').value = saved.itinerary.length; render(saved); }